# Use official Python base image
FROM python:3.13-slim

# Set working directory inside container
WORKDIR /app

# Copy files into container
COPY app.py .

# Command to run the app
CMD ["python", "app.py"]